version: '3.5'

networks:
    val_monitoring_network:

volumes:
    prometheus_master_data: {}
    prometheus_slave_data: {}
    grafana_data: {}


services:

        prometheus-master:
            container_name: prometheus-master
            image: prom/prometheus
            labels:
                org.label-schema.group: "val-monitoring"
            networks:
                - val_monitoring_network
            volumes:
                - ./configs/prometheus-master/prometheus.yml:/etc/prometheus/prometheus.yml
                - prometheus_master_data:/prometheus
            ports:
                - "9090:9090"
            command:
                - '--config.file=/etc/prometheus/prometheus.yml'
                #- '-alertmanager.url=http://alertmanager:9093' # ALERTMANAGER URL inside Docker networks
                #################################################
                - '--storage.tsdb.path=/prometheus'
                - '--web.console.libraries=/etc/prometheus/console_libraries'
                - '--web.console.templates=/etc/prometheus/consoles'
            restart: unless-stopped

        prometheus-slave:
            container_name: prometheus-slave
            image: prom/prometheus
            labels:
                org.label-schema.group: "val-monitoring"
            networks:
                - val_monitoring_network
            volumes:
                - ./configs/prometheus-slave/prometheus.yml:/etc/prometheus/prometheus.yml
                - ./configs/prometheus-slave/records/node_exporter_recording.rules:/etc/prometheus/node_exporter_recording.rules
                - ./configs/prometheus-slave/alerts/node_stats.rules:/etc/prometheus/node_stats.rules
                - prometheus_slave_data:/prometheus
            ports:
                - "9099:9090"
            command:
                - '--config.file=/etc/prometheus/prometheus.yml'
                #################################################
                - '--storage.tsdb.path=/prometheus'
                - '--web.console.libraries=/etc/prometheus/console_libraries'
                - '--web.console.templates=/etc/prometheus/consoles'
            # restart: unless-stopped

        grafana_dashboard:
            container_name: grafana_dashboard_federation
            image: grafana/grafana
            networks:
                - val_monitoring_network
            volumes:
                - grafana_data:/etc/grafana
            environment:
                - TERM=linux
                - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
                - GF_SECURITY_ADMIN_USER=admin
                - GF_SECURITY_ADMIN_PASSWORD=admin123456
            ports:
                - "3000:3000"

        node_exporter:
            image: quay.io/prometheus/node-exporter:latest
            container_name: node_exporter_stats
            networks:
                - val_monitoring_network
            ports:
                - "9100:9100"
            expose:
                - "9100"
            # restart: unless-stopped

        alertmanager:
            image: prom/alertmanager
            container_name: alertmanager
            volumes:
                - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
            ports:
                - "9093:9093"
