version: '3.5'

networks:
    monitoring_network:

volumes:
    prometheus_leader_data: {}
    prometheus_follower_1_data: {}
    prometheus_follower_2_data: {}
    grafana_leader_data: {}
    grafana_follower_data: {}

services:
    prometheus-leader:
        container_name: prometheus-leader
        image: prom/prometheus
        networks:
            - monitoring_network
        volumes:
            - ./configs/prometheus-leader/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./configs/prometheus-leader/alerts/alert.rules:/etc/prometheus/alert.rules
            - prometheus_leader_data:/prometheus
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
        restart: unless-stopped

    prometheus-follower-1:
        container_name: prometheus-follower-1
        image: prom/prometheus
        networks:
            - monitoring_network
        volumes:
            - ./configs/prometheus-follower-1/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./configs/prometheus-follower-1/records/node_exporter_recording.rules:/etc/prometheus/node_exporter_recording.rules
            - ./configs/prometheus-follower-1/alerts/node_exporter_alert.rules:/etc/prometheus/node_exporter_alert.rules
            - prometheus_follower_1_data:/prometheus
        ports:
            - "9098:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
        restart: unless-stopped

    prometheus-follower-2:
        container_name: prometheus-follower-2
        image: prom/prometheus
        networks:
            - monitoring_network
        volumes:
            - ./configs/prometheus-follower-2/prometheus.yml:/etc/prometheus/prometheus.yml
            # - ./configs/prometheus-follower-2/records/node_exporter_recording.rules:/etc/prometheus/node_exporter_recording.rules
            # - ./configs/prometheus-follower-2/alerts/node_exporter_alert.rules:/etc/prometheus/node_exporter_alert.rules
            - prometheus_follower_2_data:/prometheus
        ports:
            - "9099:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
        restart: unless-stopped

    grafana_leader:
        container_name: grafana_leader
        image: grafana/grafana
        networks:
            - monitoring_network
        volumes:
            - ./configs/grafana-leader/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - ./configs/grafana-leader/provisioning/datasources/config.yml:/etc/grafana/provisioning/datasources/config.yml
            - grafana_leader_data:/etc/grafana
        environment:
            - TERM=linux
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin123456
        ports:
            - "3000:3000"
        restart: unless-stopped

    grafana_follower:
        container_name: grafana_follower
        image: grafana/grafana
        networks:
            - monitoring_network
        volumes:
            - ./configs/grafana-follower/provisioning/dashboards:/etc/grafana/provisioning/dashboards
            - ./configs/grafana-follower/provisioning/datasources/config.yml:/etc/grafana/provisioning/datasources/config.yml
            - grafana_follower_data:/etc/grafana
        environment:
            - TERM=linux
            - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin123456
        ports:
            - "3001:3000"
        restart: unless-stopped

    node_exporter:
        image: quay.io/prometheus/node-exporter:latest
        container_name: node_exporter_stats
        networks:
            - monitoring_network
        ports:
            - "9100:9100"
        expose:
            - "9100"
        restart: unless-stopped

    blackbox_exporter:
        image: prom/blackbox-exporter
        container_name: blackbox_exporter
        networks:
            - monitoring_network
        ports:
            - "9115:9115"
        restart: unless-stopped

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        networks:
            - monitoring_network
        volumes:
            - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - "9093:9093"
        restart: unless-stopped

    dingtalk-robot:
        image: timonwong/prometheus-webhook-dingtalk
        container_name: dingtalk-robot
        networks:
            - monitoring_network
        ports:
            - "8060:8060"
        volumes:
            - ./configs/dingtalk/config.yml:/etc/prometheus-webhook-dingtalk/config.yml
        restart: unless-stopped


    cadvisor:
      image: google/cadvisor:latest
      container_name: cadvisor
      ports:
        - 8080:8080
      networks:
        - monitoring_network
      restart: unless-stopped
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
