---

global:

  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-follower'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - node_exporter_recording.rules
  # - node_exporter_alert.rules

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:

  - job_name: "node"
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter_stats:9100']

  # - job_name: 'prometheus'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['localhost:9090']