version: '3.5'

networks:
    monitoring_network:

services:

    node_exporter:
        image: prom/node-exporter:latest
        container_name: node_exporter
        networks:
            - monitoring_network
        ports:
            - "9100:9100"
        expose:
            - "9100"
        restart: unless-stopped

    cadvisor:
      image: google/cadvisor:latest
      container_name: cadvisor
      ports:
        - 8088:8080
      networks:
        - monitoring_network
      restart: unless-stopped
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
