route:
  group_by: [alertname, job]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 10m
  receiver: 'send_to_slack_webhook'
receivers:
- name: 'send_to_slack_webhook'
  slack_configs:
    - api_url: 'https://hooks.slack.com/services/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'
      channel: "#alertmanager"
      send_resolved: true
